### ISSUE TITLE
hf_recv error

### ISSUE THREAD

**Issue by marceloparavisi** [andersondomingues/orca-sim#10]
Hello Anderson

I was testing "example-orca-udp" and the returned msg was not correct. The output was:

> [ INFO] [1560961567.053192095]: r: "", 9 bytes (0:62:20)

The msg was empty, although It was received 9 bytes. Since the msg was incorrect, when the command "orca_mpsoc_to_ros.publish(msg)" was executed, a segmentation fault event has emerged.

Regards,
Marcelo

**Comment by andersondomingues** [comment]
Fixed in [d5fdbc2](https://github.com/andersondomingues/ursa/commit/d5fdbc2eb6d32f5712624797cdeac8826c778e91).
