### ISSUE TITLE
Default application 

### ISSUE THREAD

**Issue by marceloparavisi** [andersondomingues/orca-sim#7]
The default application configured into 

https://github.com/andersondomingues/ursa/blob/stable/software/orca-lib/src/orca-lib.c 

isnt the same of 

https://github.com/andersondomingues/ursa/blob/stable/Configuration.mk.

**Comment by andersondomingues** [comment]
Fixed in [674f915](https://github.com/andersondomingues/ursa/commit/674f915af2ef31a84f2a31867b698a7409af8c00).
